insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'청담인한의원' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'TLC 메디버스' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'한컴케어링크' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'플레이투큐어' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'라메디텍' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10003,  N'바이오세상' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'서울대학교 국제기술농업대학원' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'한국공과대학교' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'광주과학기술원' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'메타젤리스' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'대신증권' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'부산정보산업진흥원' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'모모보드' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'몰리즈' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'BMC KOREA' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10006,  N'유나인체인지' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'한국예총' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'심심이' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'다비다' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'지디넷코리아' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'라이팅젤' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'제인토스' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10007,  N'청하우' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10101,  N'팩터 M-X' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10102,  N'아침편지문화재단' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10103,  N'슈피겐 코리아' );
insert into mapExposulBrand ( mapExposulInfoId, brandName ) values ( 10104,  N'레드페이스' );