use tcgprojectdb
go

begin transaction;


-- tablename : avatarParts
update avatarParts set id = 1000,avatarPartsType = 1,chatId = 101,prefabName = N'CG_A_Hair001',materialName = N'CG_A_Hair001',thumbnailName = N'T_Hair001',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'숏 헤어',nameId = 2001,sizeType = 1,colorType = 1,groupType = 1 where id=1000;
update avatarParts set id = 1001,avatarPartsType = 1,chatId = 102,prefabName = N'CG_A_Hair002',materialName = N'CG_A_Hair002',thumbnailName = N'T_Hair002',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'롱 헤어',nameId = 2002,sizeType = 1,colorType = 1,groupType = 1 where id=1001;
update avatarParts set id = 1002,avatarPartsType = 1,chatId = 103,prefabName = N'CG_A_Hair003',materialName = N'CG_A_Hair003',thumbnailName = N'T_Hair003',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'그레이 모자 헤어',nameId = 2003,sizeType = 1,colorType = 1,groupType = 1 where id=1002;
update avatarParts set id = 1003,avatarPartsType = 1,chatId = 104,prefabName = N'CG_A_Hair003',materialName = N'CG_A_Hair003_1',thumbnailName = N'T_Hair004',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'퍼플 모자 헤어',nameId = 2004,sizeType = 1,colorType = 1,groupType = 1 where id=1003;
update avatarParts set id = 1004,avatarPartsType = 1,chatId = 105,prefabName = N'CG_A_Hair003',materialName = N'CG_A_Hair003_2',thumbnailName = N'T_Hair005',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 해골모자 헤어',nameId = 2005,sizeType = 1,colorType = 1,groupType = 1 where id=1004;
update avatarParts set id = 1005,avatarPartsType = 1,chatId = 106,prefabName = N'CG_A_Hair003',materialName = N'CG_A_Hair003_3',thumbnailName = N'T_Hair006',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 해골모자 헤어',nameId = 2006,sizeType = 1,colorType = 1,groupType = 1 where id=1005;
update avatarParts set id = 1006,avatarPartsType = 1,chatId = 107,prefabName = N'CG_A_Hair004',materialName = N'CG_A_Hair004',thumbnailName = N'T_Hair007',effectName = N'EF_heart',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'핑크 양갈래 헤어',nameId = 2007,sizeType = 1,colorType = 1,groupType = 1 where id=1006;
update avatarParts set id = 1007,avatarPartsType = 1,chatId = 108,prefabName = N'CG_A_Hair005',materialName = N'CG_A_Hair005',thumbnailName = N'T_Hair008',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'그레이 올백 헤어',nameId = 2008,sizeType = 1,colorType = 1,groupType = 1 where id=1007;
update avatarParts set id = 1008,avatarPartsType = 1,chatId = 109,prefabName = N'CG_A_Hair006',materialName = N'CG_A_Hair006',thumbnailName = N'T_Hair009',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'브라운 헤어',nameId = 2009,sizeType = 1,colorType = 1,groupType = 1 where id=1008;
update avatarParts set id = 1009,avatarPartsType = 1,chatId = 110,prefabName = N'CG_A_Hair007',materialName = N'CG_A_Hair007',thumbnailName = N'T_Hair010',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 헤어',nameId = 2010,sizeType = 1,colorType = 1,groupType = 1 where id=1009;
update avatarParts set id = 1010,avatarPartsType = 1,chatId = 111,prefabName = N'CG_A_Hair008',materialName = N'CG_A_Hair008',thumbnailName = N'T_Hair011',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'꽁지 헤어',nameId = 2011,sizeType = 1,colorType = 1,groupType = 1 where id=1010;
update avatarParts set id = 1011,avatarPartsType = 1,chatId = 112,prefabName = N'CG_A_Hair009',materialName = N'CG_A_Hair009',thumbnailName = N'T_Hair012',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블론드 올백 헤어',nameId = 2012,sizeType = 1,colorType = 1,groupType = 1 where id=1011;
update avatarParts set id = 1012,avatarPartsType = 1,chatId = 113,prefabName = N'CG_A_Hair010',materialName = N'CG_A_Hair010',thumbnailName = N'T_Hair013',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'옐로우 헤어',nameId = 2013,sizeType = 1,colorType = 1,groupType = 1 where id=1012;
update avatarParts set id = 1013,avatarPartsType = 1,chatId = 114,prefabName = N'CG_A_Hair011',materialName = N'CG_A_Hair011',thumbnailName = N'T_Hair014',effectName = N'EF_smoke_01',aniName = N'emote_hi',divisionType = 2,questText = 701,description = N'공룡 머리',nameId = 2014,sizeType = 1,colorType = 1,groupType = 1 where id=1013;
update avatarParts set id = 1014,avatarPartsType = 1,chatId = 115,prefabName = N'CG_A_Hair012',materialName = N'CG_A_Hair012',thumbnailName = N'T_Hair015',effectName = N'EF_fire',aniName = N'emote_hi',divisionType = 1,questText = 0,description = N'에일리언 머리',nameId = 2015,sizeType = 1,colorType = 1,groupType = 1 where id=1014;
update avatarParts set id = 1015,avatarPartsType = 1,chatId = 116,prefabName = N'CG_A_Hair013',materialName = N'CG_A_Hair013',thumbnailName = N'T_Hair016',effectName = N'EF_spark',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'퍼플 로봇머리',nameId = 2016,sizeType = 1,colorType = 1,groupType = 1 where id=1015;
update avatarParts set id = 1016,avatarPartsType = 1,chatId = 117,prefabName = N'CG_A_Hair014',materialName = N'CG_A_Hair014',thumbnailName = N'T_Hair017',effectName = N'EF_spark',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'핑크 로봇머리',nameId = 2017,sizeType = 1,colorType = 1,groupType = 1 where id=1016;
update avatarParts set id = 1017,avatarPartsType = 1,chatId = 118,prefabName = N'CG_A_Hair015',materialName = N'CG_A_Hair015',thumbnailName = N'T_Hair018',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'썬캡 펌 헤어',nameId = 2018,sizeType = 1,colorType = 1,groupType = 1 where id=1017;
update avatarParts set id = 1018,avatarPartsType = 1,chatId = 119,prefabName = N'CG_A_Hair016',materialName = N'CG_A_Hair016',thumbnailName = N'T_Hair019',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'레드 웨이브 헤어',nameId = 2019,sizeType = 1,colorType = 1,groupType = 1 where id=1018;
update avatarParts set id = 1019,avatarPartsType = 1,chatId = 120,prefabName = N'CG_A_Hair017',materialName = N'CG_A_Hair017',thumbnailName = N'T_Hair020',effectName = N'EF_Costume_03',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'홍길동 화이트 폼 헤어',nameId = 2020,sizeType = 1,colorType = 1,groupType = 1 where id=1019;
update avatarParts set id = 1020,avatarPartsType = 1,chatId = 121,prefabName = N'CG_A_Hair017',materialName = N'CG_A_Hair017_1',thumbnailName = N'T_Hair021',effectName = N'EF_Costume_04',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'홍길동 레드 폼 헤어',nameId = 2021,sizeType = 1,colorType = 1,groupType = 1 where id=1020;
update avatarParts set id = 1021,avatarPartsType = 1,chatId = 122,prefabName = N'CG_A_Hair018',materialName = N'CG_A_Hair018',thumbnailName = N'T_Hair022',effectName = N'EF_Costume_05',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'노란 두건 헤어',nameId = 2022,sizeType = 1,colorType = 1,groupType = 1 where id=1021;
update avatarParts set id = 1022,avatarPartsType = 1,chatId = 123,prefabName = N'CG_A_Hair018',materialName = N'CG_A_Hair018_1',thumbnailName = N'T_Hair023',effectName = N'EF_Costume_06',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 두건 헤어',nameId = 2023,sizeType = 1,colorType = 1,groupType = 1 where id=1022;
update avatarParts set id = 1023,avatarPartsType = 1,chatId = 124,prefabName = N'CG_A_Hair019',materialName = N'CG_A_Hair019',thumbnailName = N'T_Hair024',effectName = N'EF_Costume_07',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'할머니 헤어',nameId = 2024,sizeType = 1,colorType = 1,groupType = 1 where id=1023;
update avatarParts set id = 1024,avatarPartsType = 1,chatId = 125,prefabName = N'CG_A_Hair020',materialName = N'CG_A_Hair020',thumbnailName = N'T_Hair025',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'기본 갓',nameId = 2025,sizeType = 1,colorType = 1,groupType = 1 where id=1024;
update avatarParts set id = 1025,avatarPartsType = 1,chatId = 126,prefabName = N'CG_A_Hair021',materialName = N'CG_A_Hair021',thumbnailName = N'T_Hair026',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'꽃 장식 쪽진머리',nameId = 2026,sizeType = 1,colorType = 1,groupType = 1 where id=1025;
update avatarParts set id = 1026,avatarPartsType = 1,chatId = 125,prefabName = N'CG_A_Hair022',materialName = N'CG_A_Hair022',thumbnailName = N'T_Hair027',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'옥 장식 흑립',nameId = 2027,sizeType = 1,colorType = 1,groupType = 1 where id=1026;
update avatarParts set id = 1027,avatarPartsType = 1,chatId = 126,prefabName = N'CG_A_Hair023',materialName = N'CG_A_Hair023',thumbnailName = N'T_Hair028',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'옥비녀 쪽진머리',nameId = 2028,sizeType = 1,colorType = 1,groupType = 1 where id=1027;
update avatarParts set id = 1028,avatarPartsType = 1,chatId = 127,prefabName = N'CG_A_Hair024',materialName = N'CG_A_Hair024',thumbnailName = N'T_Hair029',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'유관순 댕기머리',nameId = 2029,sizeType = 1,colorType = 1,groupType = 1 where id=1028;
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (1029,1,128,N'CG_Avatar_hair025',N'CG_Avatar_hair025',N'T_Hair030',N'EF_Costume_01',N'emote_hi',3,716,N'로고 볼캡',2154,2,5,12);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (1030,1,129,N'CG_Avatar_hair025',N'CG_Avatar_hair025_1',N'T_Hair031',N'EF_Costume_01',N'action_idle02',3,716,N'CNCT 볼캡',2155,2,4,12);
update avatarParts set id = 2000,avatarPartsType = 2,chatId = 201,prefabName = N'CG_A_Top001',materialName = N'CG_A_Top001_2',thumbnailName = N'T_Top003',effectName = N'EF_Costume_02',aniName = N'emote_followme',divisionType = 1,questText = 0,description = N'화이트 반팔티',nameId = 2030,sizeType = 1,colorType = 1,groupType = 1 where id=2000;
update avatarParts set id = 2001,avatarPartsType = 2,chatId = 202,prefabName = N'CG_A_Top001',materialName = N'CG_A_Top001_1',thumbnailName = N'T_Top002',effectName = N'EF_Costume_02',aniName = N'emote_followme',divisionType = 2,questText = 0,description = N'블랙 해골 반팔티',nameId = 2031,sizeType = 1,colorType = 1,groupType = 1 where id=2001;
update avatarParts set id = 2002,avatarPartsType = 2,chatId = 203,prefabName = N'CG_A_Top001',materialName = N'CG_A_Top001',thumbnailName = N'T_Top001',effectName = N'EF_Costume_02',aniName = N'emote_followme',divisionType = 1,questText = 0,description = N'힙합 반팔티',nameId = 2032,sizeType = 1,colorType = 1,groupType = 1 where id=2002;
update avatarParts set id = 2003,avatarPartsType = 2,chatId = 204,prefabName = N'CG_A_Top001',materialName = N'CG_A_Top001_3',thumbnailName = N'T_Top004',effectName = N'EF_Costume_02',aniName = N'emote_followme',divisionType = 1,questText = 0,description = N'블랙 반팔티',nameId = 2033,sizeType = 1,colorType = 1,groupType = 1 where id=2003;
update avatarParts set id = 2004,avatarPartsType = 2,chatId = 205,prefabName = N'CG_A_Top001',materialName = N'CG_A_Top001_4',thumbnailName = N'T_Top005',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'스마일 반팔티',nameId = 2034,sizeType = 1,colorType = 1,groupType = 1 where id=2004;
update avatarParts set id = 2005,avatarPartsType = 2,chatId = 206,prefabName = N'CG_A_Top002',materialName = N'CG_A_Top002',thumbnailName = N'T_Top006',effectName = N'EF_Costume_02',aniName = N'emote_talk02',divisionType = 1,questText = 0,description = N'화이트 셔츠',nameId = 2035,sizeType = 1,colorType = 1,groupType = 1 where id=2005;
update avatarParts set id = 2006,avatarPartsType = 2,chatId = 207,prefabName = N'CG_A_Top002',materialName = N'CG_A_Top002_1',thumbnailName = N'T_Top007',effectName = N'EF_Costume_02',aniName = N'emote_talk02',divisionType = 1,questText = 0,description = N'레드 체크셔츠',nameId = 2036,sizeType = 1,colorType = 1,groupType = 1 where id=2006;
update avatarParts set id = 2007,avatarPartsType = 2,chatId = 208,prefabName = N'CG_A_Top002',materialName = N'CG_A_Top002_2',thumbnailName = N'T_Top008',effectName = N'EF_Costume_02',aniName = N'emote_talk01',divisionType = 1,questText = 0,description = N'블루 체크셔츠',nameId = 2037,sizeType = 1,colorType = 1,groupType = 1 where id=2007;
update avatarParts set id = 2008,avatarPartsType = 2,chatId = 209,prefabName = N'CG_A_Top002',materialName = N'CG_A_Top002_3',thumbnailName = N'T_Top009',effectName = N'EF_Costume_02',aniName = N'emote_talk01',divisionType = 1,questText = 0,description = N'블랙 셔츠',nameId = 2038,sizeType = 1,colorType = 1,groupType = 1 where id=2008;
update avatarParts set id = 2009,avatarPartsType = 2,chatId = 210,prefabName = N'CG_A_Top003',materialName = N'CG_A_Top003',thumbnailName = N'T_Top010',effectName = N'EF_Costume_02',aniName = N'emote_emotion',divisionType = 1,questText = 0,description = N'프릴 리본 블라우스',nameId = 2039,sizeType = 1,colorType = 1,groupType = 1 where id=2009;
update avatarParts set id = 2010,avatarPartsType = 2,chatId = 211,prefabName = N'CG_A_Top004',materialName = N'CG_A_Top004',thumbnailName = N'T_Top011',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 민소매',nameId = 2040,sizeType = 1,colorType = 1,groupType = 1 where id=2010;
update avatarParts set id = 2011,avatarPartsType = 2,chatId = 212,prefabName = N'CG_A_Top004',materialName = N'CG_A_Top004_1',thumbnailName = N'T_Top012',effectName = N'EF_Costume_02',aniName = N'emote_emotion',divisionType = 2,questText = 702,description = N'팝아트 민소매',nameId = 2041,sizeType = 1,colorType = 1,groupType = 1 where id=2011;
update avatarParts set id = 2012,avatarPartsType = 2,chatId = 213,prefabName = N'CG_A_Top004',materialName = N'CG_A_Top004_2',thumbnailName = N'T_Top013',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 2,questText = 703,description = N'무지개 민소매',nameId = 2042,sizeType = 1,colorType = 1,groupType = 1 where id=2012;
update avatarParts set id = 2013,avatarPartsType = 2,chatId = 214,prefabName = N'CG_A_Top004',materialName = N'CG_A_Top004_3',thumbnailName = N'T_Top014',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 2,questText = 704,description = N'블루 민소매',nameId = 2043,sizeType = 1,colorType = 1,groupType = 1 where id=2013;
update avatarParts set id = 2014,avatarPartsType = 2,chatId = 215,prefabName = N'CG_A_Top005',materialName = N'CG_A_Top005',thumbnailName = N'T_Top015',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'크롭 반팔티',nameId = 2044,sizeType = 1,colorType = 1,groupType = 1 where id=2014;
update avatarParts set id = 2015,avatarPartsType = 2,chatId = 216,prefabName = N'CG_A_Top005',materialName = N'CG_A_Top005_1',thumbnailName = N'T_Top016',effectName = N'EF_heart',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'세라 반팔티',nameId = 2045,sizeType = 1,colorType = 1,groupType = 1 where id=2015;
update avatarParts set id = 2016,avatarPartsType = 2,chatId = 217,prefabName = N'CG_A_Top005',materialName = N'CG_A_Top005_2',thumbnailName = N'T_Top017',effectName = N'EF_heart',aniName = N'action_idle02',divisionType = 2,questText = 705,description = N'핑크러버 반팔티',nameId = 2046,sizeType = 1,colorType = 1,groupType = 1 where id=2016;
update avatarParts set id = 2023,avatarPartsType = 2,chatId = 224,prefabName = N'CG_A_Top007',materialName = N'CG_A_Top007',thumbnailName = N'T_Top024',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 정장 자켓',nameId = 2053,sizeType = 1,colorType = 1,groupType = 1 where id=2023;
update avatarParts set id = 2024,avatarPartsType = 2,chatId = 225,prefabName = N'CG_A_Top008',materialName = N'CG_A_Top008',thumbnailName = N'T_Top025',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 2,questText = 706,description = N'트레이닝 자켓',nameId = 2054,sizeType = 1,colorType = 1,groupType = 1 where id=2024;
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2025,2,226,N'CG_Avatar_Top009',N'CG_Avatar_Top009',N'T_Top026',N'EF_Costume_01',N'action_idle02',3,716,N'나일론 아노락 하프집업 아이보리 점퍼',2129,2,2,2);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2026,2,227,N'CG_Avatar_Top009',N'CG_Avatar_Top009_1',N'T_Top027',N'EF_Costume_01',N'emote_talk01',3,716,N'나일론 아노락 하프집업 베이지 점퍼',2130,2,3,2);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2027,2,228,N'CG_Avatar_Top009',N'CG_Avatar_Top009_2',N'T_Top028',N'EF_Costume_01',N'emote_clap',3,716,N'나일론 아노락 하프집업 블랙 점퍼',2131,2,4,2);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2028,2,229,N'CG_Avatar_Top012',N'CG_Avatar_top012',N'T_Top029',N'EF_Costume_01',N'emote_hi',3,716,N'나일론 바람막이 아이보리 점퍼',2132,2,2,3);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2029,2,230,N'CG_Avatar_Top012',N'CG_Avatar_top012_1',N'T_Top030',N'EF_Costume_01',N'emote_talk02',3,716,N'나일론 바람막이 베이지 점퍼',2133,2,3,3);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2030,2,231,N'CG_Avatar_Top012',N'CG_Avatar_top012_2',N'T_Top031',N'EF_Costume_01',N'action_idle02',3,716,N'나일론 바람막이 블랙 점퍼',2134,2,4,3);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2031,2,232,N'CG_Avatar_Top001',N'CG_Avatar_top001_5',N'T_Top032',N'EF_Costume_01',N'emote_cute',3,716,N'시그니처 로고 화이트 티셔츠',2135,2,5,4);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2032,2,233,N'CG_Avatar_Top001',N'CG_Avatar_top001_6',N'T_Top033',N'EF_Costume_01',N'action_idle02',3,716,N'시그니처 로고 카키 티셔츠',2136,2,6,4);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2033,2,234,N'CG_Avatar_Top001',N'CG_Avatar_top001_7',N'T_Top034',N'EF_Costume_01',N'emote_cute',3,716,N'시그니처 로고 블랙 티셔츠',2137,2,4,4);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2034,2,235,N'CG_Avatar_Top008',N'CG_Avatar_top008_1',N'T_Top035',N'EF_Costume_01',N'emote_talk02',3,716,N'코튼 아노락 그레이 점퍼',2138,2,7,5);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2035,2,236,N'CG_Avatar_Top008',N'CG_Avatar_top008_2',N'T_Top036',N'EF_Costume_01',N'emote_hi',3,716,N'코튼 아노락 네이비 점퍼',2139,2,8,5);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2036,2,237,N'CG_Avatar_Top011',N'CG_Avatar_Top011',N'T_Top038',N'EF_Costume_01',N'action_idle02',3,716,N'부클 로고 그레이 스웻셔츠',2140,2,7,6);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2037,2,238,N'CG_Avatar_Top011',N'CG_Avatar_Top011_1',N'T_Top039',N'EF_Costume_01',N'emote_talk04',3,716,N'부클 로고 네이비 스웻셔츠',2141,2,8,6);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2038,2,239,N'CG_Avatar_Top013',N'CG_Avatar_Top013',N'T_Top040',N'EF_Costume_01',N'emote_talk01',3,716,N'하프집업 아이보리 스웻셔츠',2142,2,2,7);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (2039,2,240,N'CG_Avatar_Top013',N'CG_Avatar_Top013_1',N'T_Top041',N'EF_Costume_01',N'action_idle02',3,716,N'하프집업 네이비 스웻셔츠',2143,2,8,7);
update avatarParts set id = 3000,avatarPartsType = 3,chatId = 301,prefabName = N'CG_A_Bot001',materialName = N'CG_A_Bot001',thumbnailName = N'T_Bot001',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 반바지',nameId = 2055,sizeType = 1,colorType = 1,groupType = 1 where id=3000;
update avatarParts set id = 3001,avatarPartsType = 3,chatId = 302,prefabName = N'CG_A_Bot002',materialName = N'CG_A_Bot002',thumbnailName = N'T_Bot002',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'베이지 반바지',nameId = 2056,sizeType = 1,colorType = 1,groupType = 1 where id=3001;
update avatarParts set id = 3002,avatarPartsType = 3,chatId = 303,prefabName = N'CG_A_Bot003',materialName = N'CG_A_Bot003',thumbnailName = N'T_Bot003',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'진청 청바지',nameId = 2057,sizeType = 1,colorType = 1,groupType = 1 where id=3002;
update avatarParts set id = 3003,avatarPartsType = 3,chatId = 304,prefabName = N'CG_A_Bot004',materialName = N'CG_A_Bot004',thumbnailName = N'T_Bot004',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'연청 청바지',nameId = 2058,sizeType = 1,colorType = 1,groupType = 1 where id=3003;
update avatarParts set id = 3004,avatarPartsType = 3,chatId = 305,prefabName = N'CG_A_Bot004',materialName = N'CG_A_Bot004_1',thumbnailName = N'T_Bot005',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 긴바지',nameId = 2059,sizeType = 1,colorType = 1,groupType = 1 where id=3004;
update avatarParts set id = 3005,avatarPartsType = 3,chatId = 306,prefabName = N'CG_A_Bot005',materialName = N'CG_A_Bot005',thumbnailName = N'T_Bot006',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 긴바지',nameId = 2060,sizeType = 1,colorType = 1,groupType = 1 where id=3005;
update avatarParts set id = 3006,avatarPartsType = 3,chatId = 307,prefabName = N'CG_A_Bot005',materialName = N'CG_A_Bot005_1',thumbnailName = N'T_Bot007',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'카키 긴바지',nameId = 2061,sizeType = 1,colorType = 1,groupType = 1 where id=3006;
update avatarParts set id = 3007,avatarPartsType = 3,chatId = 308,prefabName = N'CG_A_Bot006',materialName = N'CG_A_Bot006',thumbnailName = N'T_Bot008',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블루체크 플리츠 스커트',nameId = 2062,sizeType = 1,colorType = 1,groupType = 1 where id=3007;
update avatarParts set id = 3008,avatarPartsType = 3,chatId = 309,prefabName = N'CG_A_Bot006',materialName = N'CG_A_Bot006_1',thumbnailName = N'T_Bot009',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 플리츠 스커트',nameId = 2063,sizeType = 1,colorType = 1,groupType = 1 where id=3008;
update avatarParts set id = 3009,avatarPartsType = 3,chatId = 310,prefabName = N'CG_A_Bot006',materialName = N'CG_A_Bot006_2',thumbnailName = N'T_Bot010',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 플리츠 스커트',nameId = 2064,sizeType = 1,colorType = 1,groupType = 1 where id=3009;
update avatarParts set id = 3010,avatarPartsType = 3,chatId = 311,prefabName = N'CG_A_Bot007',materialName = N'CG_A_Bot007',thumbnailName = N'T_Bot011',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'브라운 체크 스커트',nameId = 2065,sizeType = 1,colorType = 1,groupType = 1 where id=3010;
update avatarParts set id = 3011,avatarPartsType = 3,chatId = 312,prefabName = N'CG_A_Bot007',materialName = N'CG_A_Bot007_1',thumbnailName = N'T_Bot012',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 지퍼 스커트',nameId = 2066,sizeType = 1,colorType = 1,groupType = 1 where id=3011;
update avatarParts set id = 3012,avatarPartsType = 3,chatId = 313,prefabName = N'CG_A_Bot007',materialName = N'CG_A_Bot007_2',thumbnailName = N'T_Bot013',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 지퍼 스커트',nameId = 2067,sizeType = 1,colorType = 1,groupType = 1 where id=3012;
update avatarParts set id = 3013,avatarPartsType = 3,chatId = 314,prefabName = N'CG_A_Bot008',materialName = N'CG_A_Bot008',thumbnailName = N'T_Bot014',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'그린 체크 롱스커트',nameId = 2068,sizeType = 1,colorType = 1,groupType = 1 where id=3013;
update avatarParts set id = 3014,avatarPartsType = 3,chatId = 315,prefabName = N'CG_A_Bot009',materialName = N'CG_A_Bot009',thumbnailName = N'T_Bot015',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 정장바지',nameId = 2069,sizeType = 1,colorType = 1,groupType = 1 where id=3014;
update avatarParts set id = 3015,avatarPartsType = 3,chatId = 316,prefabName = N'CG_A_Bot010',materialName = N'CG_A_Bot010',thumbnailName = N'T_Bot016',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'트레이닝 바지',nameId = 2070,sizeType = 1,colorType = 1,groupType = 1 where id=3015;
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3016,3,317,N'CG_Avatar_Bot011',N'CG_Avatar_Bot011',N'T_Bot017',N'EF_Costume_01',N'emote_clap',3,716,N'나일론 아이보리 하프 팬츠',2144,2,2,8);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3017,3,318,N'CG_Avatar_Bot011',N'CG_Avatar_Bot011_1',N'T_Bot018',N'EF_Costume_01',N'emote_talk04',3,716,N'나일론 베이지 하프 팬츠',2145,2,3,8);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3018,3,319,N'CG_Avatar_Bot011',N'CG_Avatar_Bot011_2',N'T_Bot019',N'EF_Costume_01',N'emote_hi',3,716,N'나일론 블랙 하프 팬츠',2146,2,4,8);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3019,3,320,N'CG_Avatar_Bot010',N'CG_Avatar_bot010_3',N'T_Bot020',N'EF_Costume_01',N'emote_hi',3,716,N'나일론 아이보리 조거 팬츠',2147,2,2,9);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3020,3,321,N'CG_Avatar_Bot010',N'CG_Avatar_bot010_4',N'T_Bot021',N'EF_Costume_01',N'emote_talk01',3,716,N'나일론 베이지 조거 팬츠',2148,2,3,9);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3021,3,322,N'CG_Avatar_Bot010',N'CG_Avatar_bot010_5',N'T_Bot022',N'EF_Costume_01',N'emote_cute',3,716,N'나일론 블랙 조거 팬츠',2149,2,4,9);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3022,3,323,N'CG_Avatar_Bot013',N'CG_Avatar_Bot013',N'T_Bot023',N'EF_Costume_01',N'emote_hi',3,716,N'밴드 조거 그레이 팬츠',2150,2,7,10);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3023,3,324,N'CG_Avatar_Bot013',N'CG_Avatar_Bot013_1',N'T_Bot024',N'EF_Costume_01',N'emote_clap',3,716,N'밴드 조거 네이비 팬츠',2151,2,8,10);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3024,3,325,N'CG_Avatar_bot010',N'CG_Avatar_bot010_1',N'T_Bot025',N'EF_Costume_01',N'emote_talk01',3,716,N'립 조거 아이보리 팬츠',2152,2,2,11);
insert into avatarParts(id,avatarPartsType,chatId,prefabName,materialName,thumbnailName,effectName,aniName,divisionType,questText,description,nameId,sizeType,colorType,groupType) values (3025,3,326,N'CG_Avatar_bot010',N'CG_Avatar_bot010_2',N'T_Bot026',N'EF_Costume_01',N'emote_talk04',3,716,N'립 조거 네이비 팬츠',2153,2,8,11);
update avatarParts set id = 4000,avatarPartsType = 4,chatId = 401,prefabName = N'CG_A_Sui001',materialName = N'CG_A_Sui001',thumbnailName = N'T_Sui001',effectName = N'EF_spark',aniName = N'emote_hi',divisionType = 2,questText = 707,description = N'로봇 슈트',nameId = 2071,sizeType = 1,colorType = 1,groupType = 1 where id=4000;
update avatarParts set id = 4001,avatarPartsType = 4,chatId = 402,prefabName = N'CG_A_Sui002',materialName = N'CG_A_Sui002',thumbnailName = N'T_Sui002',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'가죽 청순원피스',nameId = 2072,sizeType = 1,colorType = 1,groupType = 1 where id=4001;
update avatarParts set id = 4002,avatarPartsType = 4,chatId = 403,prefabName = N'CG_A_Sui003',materialName = N'CG_A_Sui003',thumbnailName = N'T_Sui003',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'스카이 원피스',nameId = 2073,sizeType = 1,colorType = 1,groupType = 1 where id=4002;
update avatarParts set id = 4003,avatarPartsType = 4,chatId = 404,prefabName = N'CG_A_Sui004',materialName = N'CG_A_Sui004',thumbnailName = N'T_Sui004',effectName = N'EF_smoke_01',aniName = N'emote_hi',divisionType = 2,questText = 708,description = N'공룡 슈트',nameId = 2074,sizeType = 1,colorType = 1,groupType = 1 where id=4003;
update avatarParts set id = 4004,avatarPartsType = 4,chatId = 405,prefabName = N'CG_A_Sui005',materialName = N'CG_A_Sui005',thumbnailName = N'T_Sui005',effectName = N'EF_fire',aniName = N'emote_hi',divisionType = 2,questText = 709,description = N'에일리언 슈트',nameId = 2075,sizeType = 1,colorType = 1,groupType = 1 where id=4004;
update avatarParts set id = 4005,avatarPartsType = 4,chatId = 406,prefabName = N'CG_A_Sui006',materialName = N'CG_A_Sui006',thumbnailName = N'T_Sui006',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'청멜빵 점프슈트',nameId = 2076,sizeType = 1,colorType = 1,groupType = 1 where id=4005;
update avatarParts set id = 4006,avatarPartsType = 4,chatId = 407,prefabName = N'CG_A_Sui007',materialName = N'CG_A_Sui007',thumbnailName = N'T_Sui007',effectName = N'EF_warter',aniName = N'emote_followme',divisionType = 2,questText = 710,description = N'투피스 수영복',nameId = 2077,sizeType = 1,colorType = 1,groupType = 1 where id=4006;
update avatarParts set id = 4007,avatarPartsType = 4,chatId = 408,prefabName = N'CG_A_Sui008',materialName = N'CG_A_Sui008',thumbnailName = N'T_Sui008',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'연청 점프슈트',nameId = 2078,sizeType = 1,colorType = 1,groupType = 1 where id=4007;
update avatarParts set id = 4008,avatarPartsType = 4,chatId = 409,prefabName = N'CG_A_Sui009',materialName = N'CG_A_Sui009',thumbnailName = N'T_Sui009',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'초록 수산시장 룩',nameId = 2079,sizeType = 1,colorType = 1,groupType = 1 where id=4008;
update avatarParts set id = 4009,avatarPartsType = 4,chatId = 410,prefabName = N'CG_A_Sui009',materialName = N'CG_A_Sui009_1',thumbnailName = N'T_Sui010',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'흰색 수산시장 룩',nameId = 2080,sizeType = 1,colorType = 1,groupType = 1 where id=4009;
update avatarParts set id = 4010,avatarPartsType = 4,chatId = 411,prefabName = N'CG_A_Sui009',materialName = N'CG_A_Sui010',thumbnailName = N'T_Sui011',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'파란 수산시장 룩',nameId = 2081,sizeType = 1,colorType = 1,groupType = 1 where id=4010;
update avatarParts set id = 4011,avatarPartsType = 4,chatId = 412,prefabName = N'CG_A_Sui009',materialName = N'CG_A_Sui010_1',thumbnailName = N'T_Sui012',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'블랙 수산시장 룩',nameId = 2082,sizeType = 1,colorType = 1,groupType = 1 where id=4011;
update avatarParts set id = 4012,avatarPartsType = 4,chatId = 413,prefabName = N'CG_A_Sui011',materialName = N'CG_A_Sui011',thumbnailName = N'T_Sui013',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'초록 각설이',nameId = 2083,sizeType = 1,colorType = 1,groupType = 1 where id=4012;
update avatarParts set id = 4013,avatarPartsType = 4,chatId = 414,prefabName = N'CG_A_Sui011',materialName = N'CG_A_Sui011_1',thumbnailName = N'T_Sui014',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'갈색 각설이',nameId = 2084,sizeType = 1,colorType = 1,groupType = 1 where id=4013;
update avatarParts set id = 4014,avatarPartsType = 4,chatId = 415,prefabName = N'CG_A_Sui012',materialName = N'CG_A_Sui012',thumbnailName = N'T_Sui015',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'노란 수산시장 룩',nameId = 2085,sizeType = 1,colorType = 1,groupType = 1 where id=4014;
update avatarParts set id = 4015,avatarPartsType = 4,chatId = 416,prefabName = N'CG_A_Sui012',materialName = N'CG_A_Sui012_1',thumbnailName = N'T_Sui016',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'주황 수산시장 룩',nameId = 2086,sizeType = 1,colorType = 1,groupType = 1 where id=4015;
update avatarParts set id = 4016,avatarPartsType = 4,chatId = 417,prefabName = N'CG_A_Sui013',materialName = N'CG_A_Sui013',thumbnailName = N'T_Sui017',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'푸른 몸빼바지',nameId = 2087,sizeType = 1,colorType = 1,groupType = 1 where id=4016;
update avatarParts set id = 4017,avatarPartsType = 4,chatId = 418,prefabName = N'CG_A_Sui013',materialName = N'CG_A_Sui013_1',thumbnailName = N'T_Sui018',effectName = N'EF_Costume_01',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'붉은 몸빼바지',nameId = 2088,sizeType = 1,colorType = 1,groupType = 1 where id=4017;
update avatarParts set id = 4018,avatarPartsType = 4,chatId = 419,prefabName = N'CG_A_Sui014',materialName = N'CG_A_Sui014',thumbnailName = N'T_Sui019',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'자색 남자 한복',nameId = 2089,sizeType = 1,colorType = 1,groupType = 1 where id=4018;
update avatarParts set id = 4019,avatarPartsType = 4,chatId = 419,prefabName = N'CG_A_Sui014',materialName = N'CG_A_Sui014_1',thumbnailName = N'T_Sui020',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'녹색 남자 한복',nameId = 2090,sizeType = 1,colorType = 1,groupType = 1 where id=4019;
update avatarParts set id = 4020,avatarPartsType = 4,chatId = 420,prefabName = N'CG_A_Sui015',materialName = N'CG_A_Sui015',thumbnailName = N'T_Sui021',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화사한 여자 한복',nameId = 2091,sizeType = 1,colorType = 1,groupType = 1 where id=4020;
update avatarParts set id = 4021,avatarPartsType = 4,chatId = 421,prefabName = N'CG_A_Sui016',materialName = N'CG_A_Sui016',thumbnailName = N'T_Sui022',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'남자 두루마기',nameId = 2092,sizeType = 1,colorType = 1,groupType = 1 where id=4021;
update avatarParts set id = 4022,avatarPartsType = 4,chatId = 421,prefabName = N'CG_A_Sui017',materialName = N'CG_A_Sui017',thumbnailName = N'T_Sui023',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'여자 두루마기',nameId = 2093,sizeType = 1,colorType = 1,groupType = 1 where id=4022;
update avatarParts set id = 4023,avatarPartsType = 4,chatId = 127,prefabName = N'CG_A_Sui018',materialName = N'CG_A_Sui018',thumbnailName = N'T_Sui024',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'유관순 한복',nameId = 2094,sizeType = 1,colorType = 1,groupType = 1 where id=4023;
update avatarParts set id = 5000,avatarPartsType = 5,chatId = 500,prefabName = N'CG_Avatar_shoes',materialName = N'CG_Avatar_shoes',thumbnailName = N'T_Sho000',divisionType = 1,questText = 0,description = N'신발미착용',nameId = 2095,sizeType = 1,colorType = 1,groupType = 1 where id=5000;
update avatarParts set id = 5001,avatarPartsType = 5,chatId = 501,prefabName = N'CG_A_Sho001',materialName = N'CG_A_Sho001',thumbnailName = N'T_Sho001',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 구두',nameId = 2096,sizeType = 1,colorType = 1,groupType = 1 where id=5001;
update avatarParts set id = 5002,avatarPartsType = 5,chatId = 502,prefabName = N'CG_A_Sho002',materialName = N'CG_A_Sho002',thumbnailName = N'T_Sho002',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 로우 캔버스화',nameId = 2097,sizeType = 1,colorType = 1,groupType = 1 where id=5002;
update avatarParts set id = 5003,avatarPartsType = 5,chatId = 503,prefabName = N'CG_A_Sho003',materialName = N'CG_A_Sho003',thumbnailName = N'T_Sho003',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'브라운 샌달',nameId = 2098,sizeType = 1,colorType = 1,groupType = 1 where id=5003;
update avatarParts set id = 5004,avatarPartsType = 5,chatId = 504,prefabName = N'CG_A_Sho003',materialName = N'CG_A_Sho003_1',thumbnailName = N'T_Sho004',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 2,questText = 711,description = N'카키 운동화',nameId = 2099,sizeType = 1,colorType = 1,groupType = 1 where id=5004;
update avatarParts set id = 5005,avatarPartsType = 5,chatId = 505,prefabName = N'CG_A_Sho004',materialName = N'CG_A_Sho004',thumbnailName = N'T_Sho005',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 슬리퍼',nameId = 2100,sizeType = 1,colorType = 1,groupType = 1 where id=5005;
update avatarParts set id = 5006,avatarPartsType = 5,chatId = 506,prefabName = N'CG_A_Sho004',materialName = N'CG_A_Sho004_1',thumbnailName = N'T_Sho006',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 삼선 슬리퍼',nameId = 2101,sizeType = 1,colorType = 1,groupType = 1 where id=5006;
update avatarParts set id = 5007,avatarPartsType = 5,chatId = 507,prefabName = N'CG_A_Sho004',materialName = N'CG_A_Sho004_2',thumbnailName = N'T_Sho007',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'핑크 삼선 슬리퍼',nameId = 2102,sizeType = 1,colorType = 1,groupType = 1 where id=5007;
update avatarParts set id = 5008,avatarPartsType = 5,chatId = 508,prefabName = N'CG_A_Sho004',materialName = N'CG_A_Sho004_3',thumbnailName = N'T_Sho008',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'스카이 삼선 슬리퍼',nameId = 2103,sizeType = 1,colorType = 1,groupType = 1 where id=5008;
update avatarParts set id = 5009,avatarPartsType = 5,chatId = 509,prefabName = N'CG_A_Sho005',materialName = N'CG_A_Sho005',thumbnailName = N'T_Sho009',effectName = N'EF_smoke_01',aniName = N'action_doublejump',divisionType = 2,questText = 712,description = N'분홍 토끼 슬리퍼',nameId = 2104,sizeType = 1,colorType = 1,groupType = 1 where id=5009;
update avatarParts set id = 5010,avatarPartsType = 5,chatId = 510,prefabName = N'CG_A_Sho006',materialName = N'CG_A_Sho006',thumbnailName = N'T_Sho010',effectName = N'EF_smoke_01',aniName = N'action_doublejump',divisionType = 1,questText = 0,description = N'트레이닝 런닝화',nameId = 2105,sizeType = 1,colorType = 1,groupType = 1 where id=5010;
update avatarParts set id = 5011,avatarPartsType = 5,chatId = 511,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007',thumbnailName = N'T_Sho011',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 하이 캔버스화',nameId = 2106,sizeType = 1,colorType = 1,groupType = 1 where id=5011;
update avatarParts set id = 5012,avatarPartsType = 5,chatId = 512,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_1',thumbnailName = N'T_Sho012',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'레드 하이 캔버스화',nameId = 2107,sizeType = 1,colorType = 1,groupType = 1 where id=5012;
update avatarParts set id = 5013,avatarPartsType = 5,chatId = 513,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_2',thumbnailName = N'T_Sho013',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'민트 하이 캔버스화',nameId = 2108,sizeType = 1,colorType = 1,groupType = 1 where id=5013;
update avatarParts set id = 5014,avatarPartsType = 5,chatId = 514,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_3',thumbnailName = N'T_Sho014',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'퍼플 하이 캔버스화',nameId = 2109,sizeType = 1,colorType = 1,groupType = 1 where id=5014;
update avatarParts set id = 5015,avatarPartsType = 5,chatId = 515,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_4',thumbnailName = N'T_Sho015',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블루 하이 캔버스화',nameId = 2110,sizeType = 1,colorType = 1,groupType = 1 where id=5015;
update avatarParts set id = 5016,avatarPartsType = 5,chatId = 516,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_5',thumbnailName = N'T_Sho016',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'그린 하이 캔버스화',nameId = 2111,sizeType = 1,colorType = 1,groupType = 1 where id=5016;
update avatarParts set id = 5017,avatarPartsType = 5,chatId = 517,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_6',thumbnailName = N'T_Sho017',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'옐로 하이 캔버스화',nameId = 2112,sizeType = 1,colorType = 1,groupType = 1 where id=5017;
update avatarParts set id = 5018,avatarPartsType = 5,chatId = 518,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_7',thumbnailName = N'T_Sho018',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'오렌지 하이 캔버스화',nameId = 2113,sizeType = 1,colorType = 1,groupType = 1 where id=5018;
update avatarParts set id = 5019,avatarPartsType = 5,chatId = 519,prefabName = N'CG_A_Sho007',materialName = N'CG_A_Sho007_8',thumbnailName = N'T_Sho019',effectName = N'EF_tornado',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'화이트 하이 캔버스화',nameId = 2114,sizeType = 1,colorType = 1,groupType = 1 where id=5019;
update avatarParts set id = 5020,avatarPartsType = 5,chatId = 520,prefabName = N'CG_A_Sho008',materialName = N'CG_A_Sui002',thumbnailName = N'T_Sho020',effectName = N'EF_Costume_01',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'블랙 워커',nameId = 2115,sizeType = 1,colorType = 1,groupType = 1 where id=5020;
update avatarParts set id = 5021,avatarPartsType = 5,chatId = 521,prefabName = N'CG_A_Sho009',materialName = N'CG_A_Sui003',thumbnailName = N'T_Sho021',effectName = N'EF_heart',aniName = N'emote_cute',divisionType = 1,questText = 0,description = N'레드 구두',nameId = 2116,sizeType = 1,colorType = 1,groupType = 1 where id=5021;
update avatarParts set id = 5022,avatarPartsType = 5,chatId = 522,prefabName = N'CG_A_Sho010',materialName = N'CG_A_Sui007',thumbnailName = N'T_Sho022',effectName = N'EF_warter',aniName = N'action_jumpstart',divisionType = 2,questText = 713,description = N'오리발',nameId = 2117,sizeType = 1,colorType = 1,groupType = 1 where id=5022;
update avatarParts set id = 6000,avatarPartsType = 6,chatId = 600,thumbnailName = N'T_Acc000',divisionType = 1,questText = 0,description = N'악세서리 미착용',nameId = 2118,sizeType = 1,colorType = 1,groupType = 1 where id=6000;
update avatarParts set id = 6001,avatarPartsType = 6,chatId = 601,prefabName = N'CG_A_Acc001',materialName = N'CG_A_Acc001',thumbnailName = N'T_Acc001',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 2,questText = 714,description = N'블랙 동그리 안경',nameId = 2119,sizeType = 1,colorType = 1,groupType = 1 where id=6001;
update avatarParts set id = 6002,avatarPartsType = 6,chatId = 602,prefabName = N'CG_A_Acc001',materialName = N'CG_A_Acc001_1',thumbnailName = N'T_Acc002',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'레드 동그리 안경',nameId = 2120,sizeType = 1,colorType = 1,groupType = 1 where id=6002;
update avatarParts set id = 6003,avatarPartsType = 6,chatId = 603,prefabName = N'CG_A_Acc001',materialName = N'CG_A_Acc001_2',thumbnailName = N'T_Acc003',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'골드 동그리 안경',nameId = 2121,sizeType = 1,colorType = 1,groupType = 1 where id=6003;
update avatarParts set id = 6004,avatarPartsType = 6,chatId = 604,prefabName = N'CG_A_Acc001',materialName = N'CG_A_Acc001_3',thumbnailName = N'T_Acc004',effectName = N'EF_Costume_02',aniName = N'action_idle02',divisionType = 1,questText = 0,description = N'실버 동그리 안경',nameId = 2122,sizeType = 1,colorType = 1,groupType = 1 where id=6004;
update avatarParts set id = 6005,avatarPartsType = 6,chatId = 605,prefabName = N'CG_A_Acc002',materialName = N'CG_A_Acc002',thumbnailName = N'T_Acc005',effectName = N'EF_Costume_02',aniName = N'emote_talk02',divisionType = 1,questText = 0,description = N'그레이 수염',nameId = 2123,sizeType = 1,colorType = 1,groupType = 1 where id=6005;
update avatarParts set id = 6006,avatarPartsType = 6,chatId = 606,prefabName = N'CG_A_Acc002',materialName = N'CG_A_Acc002_1',thumbnailName = N'T_Acc006',effectName = N'EF_Costume_02',aniName = N'emote_talk03',divisionType = 1,questText = 0,description = N'브라운 수염',nameId = 2124,sizeType = 1,colorType = 1,groupType = 1 where id=6006;
update avatarParts set id = 6007,avatarPartsType = 6,chatId = 607,prefabName = N'CG_A_Acc002',materialName = N'CG_A_Acc002_2',thumbnailName = N'T_Acc007',effectName = N'EF_Costume_02',aniName = N'emote_talk03',divisionType = 1,questText = 0,description = N'블랙 수염',nameId = 2125,sizeType = 1,colorType = 1,groupType = 1 where id=6007;
update avatarParts set id = 6008,avatarPartsType = 6,chatId = 608,prefabName = N'CG_A_Acc002',materialName = N'CG_A_Acc002_3',thumbnailName = N'T_Acc008',effectName = N'EF_Costume_02',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'블론드 수염',nameId = 2126,sizeType = 1,colorType = 1,groupType = 1 where id=6008;
update avatarParts set id = 6009,avatarPartsType = 6,chatId = 609,prefabName = N'CG_A_Acc002',materialName = N'CG_A_Acc002_4',thumbnailName = N'T_Acc009',effectName = N'EF_Costume_02',aniName = N'emote_talk04',divisionType = 1,questText = 0,description = N'옐로우 수염',nameId = 2127,sizeType = 1,colorType = 1,groupType = 1 where id=6009;
update avatarParts set id = 6010,avatarPartsType = 6,chatId = 610,prefabName = N'CG_A_Acc003',materialName = N'CG_A_Acc003',thumbnailName = N'T_Acc010',effectName = N'EF_mark',aniName = N'emote_talk02',divisionType = 2,questText = 715,description = N'블랙 선글라스',nameId = 2128,sizeType = 1,colorType = 1,groupType = 1 where id=6010;

-- tablename : avatarPartsColorType

-- tablename : avatarPartsGroupType

-- tablename : avatarPartsSizeType

-- tablename : avatarPartsStateType

-- tablename : avatarPartsType

-- tablename : mannequinModelType

-- tablename : departmentType

-- tablename : languageType

-- tablename : memberType

-- tablename : osType

-- tablename : providerType

-- tablename : roleType

-- tablename : npcMapPositionType

-- tablename : jumpingMatchingGameType

-- tablename : quizTimeType

-- tablename : quizAnswerType

-- tablename : questConditionType

-- tablename : questGroupType

-- tablename : questMissionType

-- tablename : questNameType

-- tablename : questOpenType

-- tablename : questRewardType

-- tablename : questStepType

-- tablename : questReward

-- tablename : quest

-- tablename : countryCode

-- tablename : faq

-- tablename : forbiddenWords

-- tablename : npcSeq

-- tablename : npcSeqAct

-- tablename : npc

-- tablename : jumpingMatchingLevel

-- tablename : quizLevel

-- tablename : quizRoundTime

-- tablename : quizQuestionAnswer
update quizQuestionAnswer set id = 1,questionId = 1,answerType = 2 where id = 1;
update quizQuestionAnswer set id = 2,questionId = 2,answerType = 2 where id = 2;
update quizQuestionAnswer set id = 6,questionId = 6,answerType = 2 where id = 6;
update quizQuestionAnswer set id = 8,questionId = 8,answerType = 2 where id = 8;
update quizQuestionAnswer set id = 9,questionId = 9,answerType = 1 where id = 9;
update quizQuestionAnswer set id = 13,questionId = 13,answerType = 1 where id = 13;
update quizQuestionAnswer set id = 15,questionId = 15,answerType = 1 where id = 15;

-- tablename : hallOfFame

-- tablename : avatarPartsPrice

-- tablename : avatarPartsSizeDetail

-- tablename : commerceZoneMannequin

-- tablename : mannequinPurchaseState

rollback;